# Generated by Django 5.2.4 on 2026-02-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskModel',
        ),
        migrations.DeleteModel(
            name='FactModel',
        ),
        migrations.DeleteModel(
            name='QuestionModel',
        ),
        migrations.DeleteModel(
            name='SayingModel',
        ),
        migrations.DeleteModel(
            name='TicketStat',
        ),
    ]
