# Generated by Django 5.2.4 on 2026-03-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_askmodel_delete_factmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=12, help_text='Возраст с которого работаем', verbose_name='Age')),
                ('number', models.BigIntegerField(default=2067172340, help_text='Общее количество доступных случайных чисел', verbose_name='Количество случайных чисел')),
                ('vk', models.PositiveIntegerField(default=148330, help_text='Количество победителей VK', verbose_name='Победителей ВК')),
                ('name', models.PositiveIntegerField(default=648049691, help_text='Сколько доступно случайных имён', verbose_name='Количество случайных имён')),
                ('nick', models.PositiveIntegerField(default=281527180, help_text='Сколько доступно случайных ников', verbose_name='Количество случайных ников')),
                ('pay', models.PositiveIntegerField(default=800, help_text='Сколько уже разыграно', verbose_name='Разыграно')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
