# Generated by Django 5.2.4 on 2026-08-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='pay',
            field=models.CharField(help_text='Сколько уже разыграно', max_length=20, verbose_name='Разыграно'),
        ),
    ]
